apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
  labels:
    {{- include "wordpress.labels" . | nindent 4 }}
data:
  WORDPRESS_DB_HOST: db.db.svc
  WORDPRESS_DB_USER: wordpress
  WORDPRESS_DB_NAME: wordpress
